name: ci
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 https://github.com/actions/checkout/releases/tag/v4.1.1
      - name: install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2 https://github.com/actions/setup-node/releases/tag/v3.8.2
        with:
          node-version: 20
      - run: npm ci --omit=optional
      - run: npm test

  docker:
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'debug')
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 https://github.com/actions/checkout/releases/tag/v4.1.1
      -
        name: install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2 https://github.com/actions/setup-node/releases/tag/v3.8.2
        with:
          node-version: 20
      - run: npm ci --omit=optional
      - run: npm test
      - run: rm -r node_modules
      - run: npm ci --omit=optional --omit=dev
      -
        name: Login to container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 https://github.com/docker/login-action/releases/tag/v3.0.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0 https://github.com/docker/metadata-action/releases/tag/v5.5.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/instrumented-dht-node
      -
        name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0 https://github.com/docker/build-push-action/releases/tag/v5.1.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  heapdump-docker:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'debug')
    runs-on: [ubuntu-latest]
    steps:
      -
        name: 'Extract tag name'
        shell: bash
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_tag
      -
        name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 https://github.com/actions/checkout/releases/tag/v4.1.1
      -
        name: install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2 https://github.com/actions/setup-node/releases/tag/v3.8.2
        with:
          node-version: 20
      - run: npm ci --omit=dev --omit=optional
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 https://github.com/docker/login-action/releases/tag/v3.0.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0 https://github.com/docker/build-push-action/releases/tag/v5.1.0
        with:
          context: .
          file: Dockerfile-with-heapdump
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/instrumented-dht-node:${{ steps.extract_tag.outputs.tag }}
